# Generated by Django 2.2.3 on 2019-07-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MisPerros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Detalles', models.CharField(max_length=500)),
                ('Foto', models.ImageField(upload_to='')),
                ('Disponibilidad', models.CharField(choices=[('D', 'Disponible'), ('N', 'No Disponible')], max_length=1)),
            ],
        ),
    ]
